---

log_level: "trace"
listen:
  type: "port"
  bind_ip: "0.0.0.0"
  port: "10000"
storage:
  type: "redis"
  configs:
    redis:
      url: "redis-db"
      port: "6379"
      db:
        note_db: "0"
        user_db: "1"
      password: ""