version: "1"

services:
  redis-db:
    image: redis:alpine
    ports:
      - 6379:6379
    container_name: redis-db
  note-go-rest-service:
    image: frankway3433/note-go-rest-service:latest

    ports:
      - 10000:10000
    depends_on:
      - redis-db
    container_name: note-go-rest-service