---

log_level: "trace"
listen:
  type: "port"
  bind_ip: "127.0.0.1"
  port: "8008"
repository:
  type: "in_memory"
  configs:
    redis:
      attr_1: "val1"
user_service:
  url: "http://127.0.0.1:8800"