### create note
POST http://127.0.0.1:8008/api/v1/notes
Content-Type: application/json

{
  "title": "title1",
  "text": "text1"
}

> {%
client.test("Note created successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

### create another note
POST http://127.0.0.1:8008/api/v1/notes
Content-Type: application/json

{
  "title": "title2",
  "text": "text2"
}

> {%
client.test("Note created successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

### get note
GET http://127.0.0.1:8008/api/v1/notes/1

> {%
client.test("Note read successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
    const type = response.contentType.mimeType;
    client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
});
%}

### get notes
GET http://127.0.0.1:8008/api/v1/notes

> {%
client.test("Notes read successfully", function() {
    client.assert(response.status === 200, "Response status is not 200");
    const type = response.contentType.mimeType;
    client.assert(type === "application/json", "Expected 'application/json' but received '" + type + "'");
});
%}

### atempt to get non-existing note
GET http://127.0.0.1:8008/api/v1/notes/999

> {%
client.test("Note was not found", function() {
  client.assert(response.status === 404, "Response status is not 404");
});
%}

### update note
PUT http://127.0.0.1:8008/api/v1/notes/1
Content-Type: application/json

{
  "title": "title3",
  "text": "text3"
}

> {%
client.test("Notes updated successfully", function() {
    client.assert(response.status === 204, "Response status is not 204");
});
%}

### atempt to update non-existing note
PUT http://127.0.0.1:8008/api/v1/notes/999
Content-Type: application/json

{
  "title": "title999",
  "text": "text999"
}

> {%
client.test("Note was not updated", function() {
  client.assert(response.status === 404, "Response status is not 404");
});
%}

### delete note
DELETE http://127.0.0.1:8008/api/v1/notes/1

> {%
client.test("Note deleted successfully", function() {
    client.assert(response.status === 204, "Response status is not 204");
});
%}

### delete another note
DELETE http://127.0.0.1:8008/api/v1/notes/2

> {%
client.test("Note deleted successfully", function() {
    client.assert(response.status === 204, "Response status is not 204");
});
%}

### atempt to delete non-existing note
DELETE http://127.0.0.1:8008/api/v1/notes/999

> {%
client.test("Note was not deleted", function() {
  client.assert(response.status === 404, "Response status is not 404");
});
%}

